#Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test1@test.com",
    "password": "12345"
}


### Signout
POST http://localhost:3000/auth/signout
### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign in an existing user 
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test1@test.com",
    "password": "12345"
}


### Find all users with a given email
GET http://localhost:3000/auth?email=adannere@ddad.com

### Delete a User with a given id 
DELETE http://localhost:3000/auth/56

### Update a user 
PATCH  http://localhost:3000/auth/1
content-type: application/json

{
    "email": "chadd@edddailey.com"
}   

### Set a color 
GET http://localhost:3000/auth/colors/red


### Set a color 
GET http://localhost:3000/auth/colors